CREATE TABLE USERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255) NOT NULL,
    ENABLED BOOLEAN NOT NULL
);


CREATE TABLE CLIENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255),
    PHONE VARCHAR(50)
);

CREATE TABLE COMPTE (
    ID VARCHAR(20) PRIMARY KEY,
    DATE_CREATION DATE NOT NULL,
    SOLDE DOUBLE NOT NULL,
    CLIENT_ID BIGINT,
    TYPE VARCHAR(20) NOT NULL,
    CODE_CLI BIGINT,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID),
    FOREIGN KEY (CODE_CLI) REFERENCES USERS(ID)
);

CREATE TABLE OPERATION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DATE_OPERATION DATE NOT NULL,
    MONTANT DOUBLE NOT NULL,
    COMPTE_ID VARCHAR(20),
    TYPE VARCHAR(20) NOT NULL,
    COMPTE_CODE_COMPTE VARCHAR(20),
    FOREIGN KEY (COMPTE_ID) REFERENCES COMPTE(ID),
    FOREIGN KEY (COMPTE_CODE_COMPTE) REFERENCES COMPTE(ID)
);

CREATE TABLE RETRAIT (
    ID BIGINT PRIMARY KEY,
    FOREIGN KEY (ID) REFERENCES OPERATION(ID)
);

CREATE TABLE VERSEMENT (
    ID BIGINT PRIMARY KEY,
    FOREIGN KEY (ID) REFERENCES OPERATION(ID)
);