name: Build and Deploy Container

env:
  AZURE_WEBAPP_NAME: weBank
  REPO: el-alaoui-el-hanafi-hicham

on:
  push:
    branches: [main]

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js (Frontend)
        uses: actions/setup-node@v4
        with:
          node-version: 18
          working-directory: web

      - name: Install & Build Frontend
        run: |
          npm ci --legacy-peer-deps
          npm run build
        working-directory: web

      - name: Set up Java (Backend)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          working-directory: ./api

      - name: Build Backend
        run: mvn --batch-mode package -DskipTests
        working-directory: ./api

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build and Push Images
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push
          docker images  # Debug

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'weBank'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  
          images: |
            ghcr.io/${{ env.REPO }}/bank-web:${{ github.sha }}  
            ghcr.io/${{ env.REPO }}/bank-api:${{ github.sha }}